# Generated by Django 5.0.6 on 2024-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(default='1', max_length=3)),
                ('text', models.CharField(max_length=200)),
                ('todo_check', models.BooleanField(default=False)),
                ('timer', models.TimeField(null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
