# Generated by Django 5.0.6 on 2024-06-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
    ]
