# Generated by Django 5.0.6 on 2024-06-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_remove_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default='1'),
        ),
    ]
