# Generated by Django 5.0.6 on 2024-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_newssave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssave',
            name='news_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='newssave',
            name='news_writing',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
